require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/imoveis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Imovel. As you add validations to Imovel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Imovel.create! valid_attributes
      get imoveis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      imovel = Imovel.create! valid_attributes
      get imovel_url(imovel)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_imovel_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      imovel = Imovel.create! valid_attributes
      get edit_imovel_url(imovel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Imovel" do
        expect {
          post imoveis_url, params: { imovel: valid_attributes }
        }.to change(Imovel, :count).by(1)
      end

      it "redirects to the created imovel" do
        post imoveis_url, params: { imovel: valid_attributes }
        expect(response).to redirect_to(imovel_url(Imovel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Imovel" do
        expect {
          post imoveis_url, params: { imovel: invalid_attributes }
        }.to change(Imovel, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post imoveis_url, params: { imovel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested imovel" do
        imovel = Imovel.create! valid_attributes
        patch imovel_url(imovel), params: { imovel: new_attributes }
        imovel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the imovel" do
        imovel = Imovel.create! valid_attributes
        patch imovel_url(imovel), params: { imovel: new_attributes }
        imovel.reload
        expect(response).to redirect_to(imovel_url(imovel))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        imovel = Imovel.create! valid_attributes
        patch imovel_url(imovel), params: { imovel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested imovel" do
      imovel = Imovel.create! valid_attributes
      expect {
        delete imovel_url(imovel)
      }.to change(Imovel, :count).by(-1)
    end

    it "redirects to the imoveis list" do
      imovel = Imovel.create! valid_attributes
      delete imovel_url(imovel)
      expect(response).to redirect_to(imoveis_url)
    end
  end
end
